package main

// Copyright (C) American Certified Brands, LLC. 2018-2019.

var StoredProcConfig = []CrudStoredProcConfig{
	{
		URIPath:             "/api/v1/register-ranch-info2",
		StoredProcedureName: "s_reg_inf2",
		AuthKey:             false,
		JWTKey:              false,
		TableNameList:       []string{"t_reg_info", "t_phone_no", "t_address", "t_email_addr"},
		ParameterList: []ParamListItem{
			{ReqVar: "id", ParamName: "p_id", AutoGen: true},
			{ReqVar: "pin_code", ParamName: "p_pin_code"},
			{ReqVar: "email", ParamName: "p_email"},
			{ReqVar: "ranch_name", ParamName: "p_ranch_name"},
			{ReqVar: "primary_phone", ParamName: "p_primary_phone"},
			{ReqVar: "address_ship", ParamName: "p_address_ship"},
			{ReqVar: "address_usps", ParamName: "p_address_usps"},
			{ReqVar: "note", ParamName: "p_note"},
		},
	},
	{
		URIPath:             "/api/v1/paper_docs",
		StoredProcedureName: "s_paper_docs",
		AuthKey:             false,
		JWTKey:              false,
		TableNameList:       []string{"t_reg_info", "t_phone_no", "t_address", "t_email_addr", "t_paper_docs"},
		ParameterList: []ParamListItem{
			{ReqVar: "id", ParamName: "p_id", AutoGen: true},
			{ReqVar: "pin_code", ParamName: "p_pin_code"},
			{ReqVar: "reg_info_id", ParamName: "p_reg_info_id"},
			{ReqVar: "email", ParamName: "p_email"},
			{ReqVar: "ranch_name", ParamName: "p_ranch_name"},
			{ReqVar: "real_name", ParamName: "p_real_name"},
			{ReqVar: "primary_phone", ParamName: "p_primary_phone"},
			{ReqVar: "address_ship", ParamName: "p_address_ship"},
			{ReqVar: "address_usps", ParamName: "p_address_usps"},
			{ReqVar: "note", ParamName: "p_note"},
		},
	},
	{
		URIPath:             "/api/v1/record_type",
		StoredProcedureName: "s_record_type",
		AuthKey:             false,
		JWTKey:              false,
		TableNameList:       []string{"t_reg_info", "t_known_record_type", "t_record_type", "t_known_record_user"},
		// CREATE or REPLACE FUNCTION s_record_type ( p_reg_info_id varchar, p_known varchar, p_other varchar, p_kept_3_years varchar, p_secure_rec varchar )
		//		, "reg_info_id"				: reg_info_id
		//		, "known"			: JSON.stringify(vv)
		//		, "other"			: JSON.stringify(ww)
		//		, "kept_3_years"	: $("#kept_3_years").val()
		//		, "secure_rec"		: $("#secure_rec").val()
		ParameterList: []ParamListItem{
			{ReqVar: "reg_info_id", ParamName: "p_reg_info_id"},
			{ReqVar: "known", ParamName: "p_known"},
			{ReqVar: "other", ParamName: "p_other"},
			{ReqVar: "kept_3_years", ParamName: "p_kept_3_years"},
			{ReqVar: "secure_rec", ParamName: "p_secure_rec"},
		},
	},
}

// Table based end points
var TableConfig = []CrudConfig{
	{
		URIPath:        "/api/v1/register-ranch-info",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_reg_info",
		InsertCols:     []string{"id", "status", "error_msg", "pin_code", "email", "ranch_name", "primary_phone", "address_ship", "address_usps", "note"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "status", "error_msg", "pin_code", "email", "ranch_name", "primary_phone", "address_ship", "address_usps", "note"},
		UpdatePkCol:    "id",
		WhereCols:      []string{"user_id", "status", "email", "ranch_name"},
	},
	{
		URIPath:        "/api/v1/t_ranch_locations",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_ranch_locations",
		InsertCols:     []string{"id", "reg_info_id", "ranch_pasture_name", "location_city_state", "note"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "ranch_pasture_name", "location_city_state", "note"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/t_employee_resp",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_employee_resp",
		InsertCols:     []string{"id", "reg_info_id", "employee_name", "duties", "note"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "employee_name", "duties", "note"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/t_reg_info",
		AuthKey:        false,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_reg_info",
		InsertCols:     []string{"id", "status", "error_msg", "pin_code", "email", "ranch_name", "primary_phone", "address_ship", "address_usps", "note"},
		InsertPkCol:    "id",
		UpdateCols: []string{"id", "status", "error_msg", "pin_code", "email", "ranch_name", "primary_phone", "address_ship", "address_usps", "note",
			"records_for_3_years", "records_secure", "n_calvs_in_program", "calvs_born_in_wy", "calvs_born_locations",
			"calvs_individual_dates", "calvs_moved_off_ranch", "calvs_moved_desc", "calvs_purchased_onsite", "calvs_purchased_desc",
			"calvs_purchased_ident", "when_apply_tags", "signature_name", "signature_digital", "signature_date", "calvs_na_prev"},
		UpdatePkCol: "id",
		WhereCols:   []string{"user_id", "status", "email", "ranch_name"},
	},
	{
		URIPath:        "/api/v1/t_known_record_type",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_known_record_type",
		InsertCols:     []string{"id", "reg_info_id", "known_record_type"},
		InsertPkCol:    "id",
	},
	{
		URIPath:        "/api/v1/t_calving_info",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_calving_info",
		InsertCols:     []string{"id", "reg_info_id", "start_date", "end_date", "n_in_group", "identification"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "start_date", "end_date", "n_in_group", "identification"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/t_paper_docs",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_paper_docs",
		InsertCols:     []string{"id", "reg_info_id", "email", "ranch_name", "real_name", "document_hash", "document_file_name"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "email", "ranch_name", "real_name", "document_hash", "document_file_name"},
		UpdatePkCol:    "id",
		WhereCols:      []string{"email", "ranch_name", "real_name", "document_hash"},
	},
	{
		URIPath:        "/api/v1/register-phone-no",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_phone_no",
		InsertCols:     []string{"id", "reg_info_id", "phone_no", "note"}, // xyzzy - add Name
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "phone_no", "note"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/register-physical-loc",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_physical_loc",
		InsertCols:     []string{"id", "reg_info_id", "geolocation", "note"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "geolocation", "note"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/register-address",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_address",
		InsertCols:     []string{"id", "reg_info_id", "address_type", "data", "note"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "address_type", "data", "note"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/register-program",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_program",
		InsertCols:     []string{"id", "reg_info_id", "programs"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "programs"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:        "/api/v1/table/t_address_type",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET"},
		TableName:      "t_address_type",
		InsertCols:     []string{"id"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id"},
		UpdatePkCol:    "id",
		ProjectedCols:  []string{"id", "address_type"},
	},
	{
		URIPath:        "/api/v1/table/t_programs",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET"},
		TableName:      "t_programs",
		InsertCols:     []string{"id", "reg_info_id", "programs"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "programs"},
		UpdatePkCol:    "id",
		WhereCols:      []string{"id", "reg_info_id", "programs"},
	},
	{
		// URIPath:        "/api/v1/table/t_reg_pin",
		URIPath:             "/api/v1/pin-code-id",
		AuthKey:             true,
		JWTKey:              false,
		MethodsAllowed:      []string{"GET"},
		TableName:           "t_reg_pin",
		WhereCols:           []string{"pin"},
		SelectRequiresWhere: true,
		ProjectedCols:       []string{"id"},
	},
	//	1. Check Ranch-Name, email-address, for valid
	//		/api/v1/ranch-name-used implemented with select
	//		/api/v1/email-name-used implemented with select
	{
		URIPath:             "/api/v1/ranch-name-used",
		AuthKey:             true,
		JWTKey:              false,
		MethodsAllowed:      []string{"GET"},
		TableName:           "t_reg_info",
		WhereCols:           []string{"ranch_name"},
		SelectRequiresWhere: true,
		ProjectedCols:       []string{"id"},
	},
	/*
	   CREATE TABLE "t_record_type" (
	   	  "id"					m4_uuid_type() DEFAULT uuid_generate_v4() not null primary key
	   	, "reg_info_id"			m4_uuid_type() not null references "t_reg_info"("id")
	   	, "record_type"			text not null	 -- JSON of record types
	   	, "updated" 			timestamp
	   	, "created" 			timestamp default current_timestamp not null
	   );
	*/
	{
		URIPath:        "/api/v1/t_record_type",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST", "PUT", "DELETE"},
		TableName:      "t_record_type",
		InsertCols:     []string{"id", "reg_info_id", "record_type"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id", "reg_info_id", "record_type"},
		UpdatePkCol:    "id",
	},
	{
		URIPath:             "/api/v1/email-addr-used",
		AuthKey:             true,
		JWTKey:              false,
		MethodsAllowed:      []string{"GET"},
		TableName:           "t_reg_info",
		WhereCols:           []string{"email"},
		SelectRequiresWhere: true,
		ProjectedCols:       []string{"id"},
	},
	{
		URIPath:        "/api/v1/table/t_email_q",
		AuthKey:        true,
		JWTKey:         false,
		MethodsAllowed: []string{"GET", "POST"},
		TableName:      "t_reg_info",
		InsertCols:     []string{"id", "input_data", "template_file_name"},
		InsertPkCol:    "id",
		UpdateCols:     []string{"id"},
		UpdatePkCol:    "id",
	},
}
