
all: Lect-14.html

FR=../01/

Lect-14.html: Lect-14.md
	markdown-cli --input=./Lect-14.md --output=Lect-14.html
	cat ${FR}/css/pre ${FR}/css/markdown.css ${FR}/css/post ../../md.css ${FR}/css/hpre Lect-14.html ${FR}/css/hpost >/tmp/Lect-14.html
	mv /tmp/Lect-14.html ./Lect-14.html


